version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: turbo-nestjs-postgres
    restart: always
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    volumes:
      - turbo_nestjs_postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  turbo_nestjs_postgres:
