name: Expo Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/app/**

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: 
      name: production-app
      url: https://expo.dev/@thlmenezes/app
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
          cache-dependency-path: '**/yarn.lock'

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x.x
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install --immutable

      - name: 🚀 Publish app
        run: yarn workspace app expo publish --non-interactive
